# Generated by Django 6.0.5 on 2026-05-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('diametro_km', models.FloatField(blank=True, null=True)),
                ('masa', models.FloatField(blank=True, null=True)),
                ('distancia_sol_mill_km', models.FloatField(blank=True, null=True)),
                ('descripcion_wikipedia', models.TextField(blank=True, null=True)),
                ('url_wikipedia', models.URLField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
