# Generated by Django 6.0.5 on 2026-05-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planeta',
            old_name='descripcion_wikipedia',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='planeta',
            old_name='imagen_url',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='planeta',
            old_name='url_wikipedia',
            new_name='wiki_url',
        ),
        migrations.AddField(
            model_name='planeta',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planeta',
            name='gravedad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planeta',
            name='lunas',
            field=models.IntegerField(default=0),
        ),
    ]
