# Generated by Django 6.0.5 on 2026-06-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_descripcion_wikipedia_planeta_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planeta',
            name='lunas',
        ),
        migrations.CreateModel(
            name='Luna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('diametro_km', models.FloatField()),
                ('anio_descubrimiento', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('wiki_url', models.URLField(blank=True)),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunas', to='web.planeta')),
            ],
        ),
    ]
